# Generated by Django 2.1.3 on 2018-12-01 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_prod', models.CharField(max_length=20)),
                ('Fecha_emision', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_cliente', models.CharField(max_length=20)),
                ('Edad_cliente', models.PositiveSmallIntegerField()),
                ('Direc_cliente', models.CharField(max_length=120)),
                ('Telf_cliente', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cant_Venta_Bebidas', models.PositiveSmallIntegerField()),
                ('Cant_Venta_Cigarro', models.PositiveSmallIntegerField()),
                ('Cant_Clientes_Atendidos', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.PositiveSmallIntegerField()),
                ('subtotal', models.PositiveSmallIntegerField()),
                ('IGV', models.PositiveSmallIntegerField()),
                ('total', models.PositiveSmallIntegerField()),
                ('Boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDiscoTK.Boleta')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_empleado', models.CharField(max_length=20)),
                ('Edad_empleado', models.PositiveSmallIntegerField()),
                ('sexo_empleado', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('cargo', models.CharField(choices=[('B', 'Barman'), ('S', 'Seguridad'), ('P', 'Portero'), ('D', 'DJ')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='concepto',
            name='Detalle_Boleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDiscoTK.Detalle_Boleta'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='Cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDiscoTK.Cliente'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='Empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDiscoTK.Empleado'),
        ),
    ]
